name: Deploy website to Storage Account

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
              
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
      with:
        source-path: Site
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
