name: Deploy website to Storage Account

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
              
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
      with:
        source-path: Site
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}

    - name: Azure service principal login
      uses: azure/login@v1
      env:
        CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        creds: ${{ env.CREDENTIALS }}

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "ResumeCDN" --name "jrmcccloud" --resource-group "Cloud-Resume-Project"
          
